#!/bin/bash



myArray=("taimen" "blueline" "crosshatch" "sargo" "bonito" "flame" "coral" "sunfish" "bramble" "redfin" "barbet" "marlin")
myArray=("crosshatch" "sargo" "bonito" "flame" "coral" "sunfish" "bramble" "redfin" "barbet" "marlin")
myArray=("sunfish")
for LIST_OF_DEVICES in ${myArray[@]}
do
 wget --wait 2 --random-wait \
      --no-clobber \
      -r -l1 --no-parent --no-directories \
      --no-verbose https://download.lineage.microg.org/$LIST_OF_DEVICES/
done

export GITHUB_TOKEN=github_pat_CHANGEME

for i in `find /tmp -type f \( -iname lineage\*m -o -iname lineage\*.zip -o -iname lineage\*img \) -printf '%f\n'`
do
echo $i
github-release upload --user biop0765 \
   --repo assorted_lineageos_backup \
   --tag $LIST_OF_DEVICES  \
   --file $i --name $i
rm -fr $i
sleep 2
done

